### ISSUE TITLE
0.0.6 Fails to compile with GHC-7.8

### ISSUE THREAD

**Issue by phadej** [fpco/weigh#16]
```
src/Weigh/GHCStats.hs:62:3: Not in scope: ‘pure’
```

I made a revision on Hackage: http://hackage.haskell.org/package/weigh-0.0.6/revisions/

Discovered in https://github.com/well-typed/generics-sop/pull/60

**Comment by chrisdone** [comment]
Oh, people are still using 7.8? No problem, I'll add it back to the CI matrix.

**Comment by chrisdone** [comment]
Fixed: https://travis-ci.org/fpco/weigh/builds/308316717

Pushed weigh-0.0.7.
