### ISSUE TITLE
Build failure with GHC-8.0.1

### ISSUE THREAD

**Issue by sjakobi** [fpco/weigh#1]
The current HEAD of `weigh` doesn't build with GHC-8.0.1:

```
~/s/weigh (master) $ stack init --force --resolver ghc-8.0.1
~/s/weigh (master) $ stack build
...
/home/simon/src/weigh/src/Weigh/GHCStats.hs:20:18: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ _ _ [RecC _ fields] _
      In the pattern: TyConI (DataD _ _ _ [RecC _ fields] _)
      In a case alternative:
          TyConI (DataD _ _ _ [RecC _ fields] _)
            -> do { total <- fmap
                               (foldl' (+) headerSize) (mapM fieldSize fields);
                    litE (IntegerL (fromIntegral total)) }
            where
                headerSize = 8
                fieldSize :: (name, strict, Type) -> Q Int64
                fieldSize (_, _, typ)
                  = case typ of {
                      ConT typeName -> ...
                      _ -> fail
                             ("Unexpected type shape: "
                              ++
                                show typ
                                ++ ". Please report this as a bug, the codebase needs updating.") }
                knownTypes :: [(Name, Int64)]
                ....

--  While building package weigh-0.0.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:weigh --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by cocreature** [comment]
This can be closed now that #2 is merged

**Comment by chrisdone** [comment]
Fixed! Thanks @sjakobi for reporting. Thanks @cocreature for fixing.
